name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout Terraform repository
        uses: actions/checkout@v2
        with:
          repository: stemdo-labs/terraform-miriam

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform plan -no-color -out=plan.tfout

      # - name: Post Plan result as PR comment
      #   if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      #   id: tfplan
      #   run: |
      #     terraform show -json plan.tfout > plan.json
      #     PLAN=$(terraform show -no-color plan.tfout)
      #     echo "Plan output: $PLAN"
      #     echo "::set-output name=plan::$PLAN"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create PR comment with plan
      #   if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     header: "Terraform Plan"
      #     message: ${{ steps.tfplan.outputs.plan }}

      # - name: Terraform Apply
      #   if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      #   env:
      #     TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      #     TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      #     TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      #   run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform destroy -auto-approve